import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/Components/Header";
import Banner from "@/Components/Banner";
import ProductFeed from "@/Components/ProductFeed";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ products }) {
  return (
    <div className="bg-gray-100">
      <Head>
        <title>Amazon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Header />

      <main className="max-w-screen-2xl mx-auto">
        <Banner />

        <ProductFeed products={products} />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const products = await fetch(
    "https://hasinduperera12.github.io/amazonAPi/amazon.json"
  ).then((res) => res.json());

  return {
    props: {
      products,
    },
  };
}

//https://fakestoreapi.com/products
